### ISSUE TITLE
fsck task fails: /etc/default/rcS does not exist

### ISSUE THREAD

**Issue by jbicha** [debops/ansible-console#39]
Ubuntu 16.04 or Debian stretch

I'm using the default lxd images ( image:debian/stretch and ubuntu:16.04 ) but I don't think that matters for this issue. I think this is because Ubuntu and Debian now use systemd by default. See also this [discussion](http://forums.debian.net/viewtopic.php?f=30&t=127172).

TASK [debops.console : Configure fsck behaviour on boot] ***********************
fatal: [alabama]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /etc/default/rcS does not exist !", "rc": 257}

Workaround
----------------
Add this to `inventory/group_vars/all/vars.yml`
`console_fsckfix: False`

**Comment by drybjed** [comment]
From reading that thread can I assume that with `systemd` now disks are fixed by `fsck` automatically, ie. `FSCKFIX=yes` is implied?

Thanks for the heads up, this task needs to be confined to older OS releases in this case.

**Comment by jbicha** [comment]
Sorry, I don't know anything about the FSCKFIX option.
