### ISSUE TITLE
hidepid=2 breaks facts.py until ansible v2.2.1.0-0.2.rc2

### ISSUE THREAD

**Issue by cultcom** [debops/ansible-console#40]
in facts.py line 335 the following check breaks after mounting /proc with hidepid=2
if proc_1 == 'init' or proc_1.endswith('sh'):

because proc_1 is "None" now.

The check was change with commit e6d9a45cd02f290feb8063baa60e8a5fbde079e0

So this breaks older versions of ansible.

**Comment by drybjed** [comment]
This issue [should be solved already](https://github.com/ansible/ansible/issues/20225) on `stable-2.2` Ansible branch, at least the one from GitHub. Version from PyPI hasn't been updated yet. Can you check and confirm?

**Comment by cultcom** [comment]
Yes, this works with stable-2.2 but I wanted to file this issue in case others are having the same problem...
