### ISSUE TITLE
Overwrite the default editor?

### ISSUE THREAD

**Issue by jankatins** [debops/ansible-console#46]
I've both vim and nano installed but want nano to be the default editor. I tried to do this in a var file:

```yaml
console_preferred_editors:
  - '/bin/nano'
```

But it seems this has not the desired effect that this is put in the first place of the list. Is there any way to set the default editor apart from removing the earlier editors in the default list? If not: would it be possible to add such a way?

**Comment by drybjed** [comment]
Agreed, the current mechanism is not flexible enough and will be redesigned in the future.

Just a heads up - DebOps development is now done in the [DebOps monorepo](https://github.com/debops/debops/), you might want to consider switching over to it.

**Comment by jankatins** [comment]
Thanks for the info, still a bit new how all of debops works together...

Put it here: https://github.com/debops/debops/issues/234
