### ISSUE TITLE
Manage Root Password

### ISSUE THREAD

**Issue by MatthewMi11er** [debops/ansible-console#5]
The most recent change (#4) adds root management which is good, but it should have the option of not having a root password at all. Meaning that password login is unavailable and only certificates can be used.

**Comment by drybjed** [comment]
@MatthewMi11er If you set `console_root` to False, password won't be changed. Then we can set the password blank in the preseeding options. Would that be an acceptable solution?

**Comment by MatthewMi11er** [comment]
@drybjed Would it make more sense to add `when console_root_password != false` or something similar on the `Enforce root user account` tasks? That way `console_root_password` can be set to `False` and the rest of `root_account.yml` can still run?

**Comment by drybjed** [comment]
Sure, I can do it this way.

**Comment by MatthewMi11er** [comment]
awsome
